// data.js
const omer = [
  { id: 1, name: "Omer A", age: 25 },
  { id: 2, name: "Omer B", age: 30 },
  { id: 3, name: "Omer C", age: 35 },
];

const TiubimIdaniimHaktzaData = [
  {
    id: 4518,
    nameKasm: 'מפק בח"א 10',
    category: "",
    madorInChargeOf: "",
    tiubExplanation: "מעבר לאזרוח מלאים",
    begda: "01-05-2024",
    endda: "31-12-2024",
    timeDiff: 1.002739726,
    comment: "תוקף מול רונית במודל טיובים 5.7.22",
    kvutzotMinuiKatzinBahir: 0,
    kvutzotMinuiKatzinMuvak: 0,
    kvutzotMinuiKatzinRishoni: 0,
    kvutzotMinuiNagadMuvak: 0,
    kvutzotMinuiNagadRishoni: -3,
    total: -3,
    munahiRishoni: -3,
  },
  {
    id: 3334,
    nameKasm: 'מפק בח"א 28',
    category: "",
    madorInChargeOf: "",
    tiubExplanation: "מעבר לאזרוח מלא במטבחים",
    begda: "01-01-2024",
    endda: "31-12-2024",
    timeDiff: 1.002739726,
    comment: "תוקף מול רונית במודל טיובים 5.7.22",
    kvutzotMinuiKatzinBahir: 0,
    kvutzotMinuiKatzinMuvak: 0,
    kvutzotMinuiKatzinRishoni: 0,
    kvutzotMinuiNagadMuvak: 0,
    kvutzotMinuiNagadRishoni: -3,
    total: -3,
    munahiRishoni: -3,
  },
  {
    id: 7171,
    nameKasm: "להק המודיעין 5619",
    category: "",
    madorInChargeOf: "",
    tiubExplanation: "סתם בדיקה",
    begda: "01-01-2024",
    endda: "31-12-2024",
    timeDiff: 1.002739726,
    comment: "סתם בדיקה הzzzערה",
    kvutzotMinuiKatzinBahir: 0,
    kvutzotMinuiKatzinMuvak: 0,
    kvutzotMinuiKatzinRishoni: 0,
    kvutzotMinuiNagadMuvak: 2,
    kvutzotMinuiNagadRishoni: 0,
    total: 2,
    munahiRishoni: 3.64,
  },
];

const TiubimIdaniimTkinaData = [
  {
    id: 4518,
    nameKasm: 'מפק בח"א 10',
    category: "",
    madorInChargeOf: "",
    tiubExplanation: "מעבר לאזרוח מלאים",
    begda: "01-01-2025",
    endda: "31-12-2025",
    timeDiff: 1.002739726,
    comment: "תקינה 1",
    kvutzotMinuiKatzinBahir: 1,
    kvutzotMinuiKatzinMuvak: 1,
    kvutzotMinuiKatzinRishoni: 0,
    kvutzotMinuiNagadMuvak: 0,
    kvutzotMinuiNagadRishoni: -3,
    total: -1,
    munahiRishoni: -3,
  },
  {
    id: 3334,
    nameKasm: 'מפק בח"א 28',
    category: "",
    madorInChargeOf: "",
    tiubExplanation: "מעבר לאזרוח מלא במטבחים",
    begda: "01-01-2025",
    endda: "31-12-2025",
    timeDiff: 1.002739726,
    comment: "תקינה 2",
    kvutzotMinuiKatzinBahir: 0,
    kvutzotMinuiKatzinMuvak: 0,
    kvutzotMinuiKatzinRishoni: 0,
    kvutzotMinuiNagadMuvak: 0,
    kvutzotMinuiNagadRishoni: -2,
    total: -2,
    munahiRishoni: -3,
  },
  {
    id: 7171,
    nameKasm: "להק המודיעין 5619",
    category: "",
    madorInChargeOf: "",
    tiubExplanation: "תקינה 3",
    begda: "01-01-2024",
    endda: "31-12-2024",
    timeDiff: 1.002739726,
    comment: "סתם בדיקה הערה",
    kvutzotMinuiKatzinBahir: 2,
    kvutzotMinuiKatzinMuvak: 1,
    kvutzotMinuiKatzinRishoni: 4,
    kvutzotMinuiNagadMuvak: 2,
    kvutzotMinuiNagadRishoni: 5,
    total: 14,
    munahiRishoni: 3.64,
  },
];

module.exports = { omer, TiubimIdaniimHaktzaData, TiubimIdaniimTkinaData };
